---

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
  become: true

- name: Restart Omicron
  systemd:
    name: '{{ omicron_application_name }}'
    state: restarted
  become: true
